# Generated by Django 5.0.3 on 2024-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('participants', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('imageUrl', models.URLField(blank=True, max_length=1024, null=True)),
                ('videoUrl', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
