version: '3.9'

services:
  django_app:
    image: eventapp_ui:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - 3000:3000
    restart: always
    user: root
    environment:
      NODE_ENV: "dev"

  # PostgreSQL service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"